---
- name: A sample playbook showing that prompt displaying the variable values
  hosts: localhost
  gather_facts: False
  tasks: 
  - name: "Prompt for user response"
    user_prompt:
      prompt: "Do you want to continue with {{action}} of {{user}} user?(y/n)?"
      passing_response: ['y','yes']
      abort_response: ['n','no']
    vars:
      action: "deletion"
      user: "foobar"

  - name: "Task next to the prompt"
    debug:
      msg: "DELETING THE USER OH!!"


